# Generate Profiles of SPP Sub-Areas
SPP: [Sothwest Power Tool](https://www.spp.org/)

The historical load data rolled up at an hourly level and grouped by *Legacy BAs* for 2015 and 2016 have been downloaded [here](https://marketplace.spp.org/pages/hourly-load).

We shift the whole year profile by 6 hours in order to make it start with the first hour in UTC time of 2016, which is consistent with our system. However, by checking the hourly difference, we found 7-hour shift has the minimum hourly difference comparing with the EIA data (both 1 hour more and less gives 10 times more total absolute differences).

In [1]:
import os
import pandas as pd

Read load data.

In [2]:
filedir = os.path.join("load", "2016")
filename_prefix = 'HOURLY_LOAD-2016'
subarea_profile_by_month = []
for i in range(1,13):
    filename = filename_prefix + str(i).zfill(2) + '.csv'
    month_i_profile = pd.read_csv(os.path.join(filedir, filename),index_col = 0)
    subarea_profile_by_month.append(month_i_profile)

The last hours of 2015 are needed since we want the profile in UTC time.

In [3]:
filedir = os.path.join("load", "2015")
filename = 'HOURLY_LOAD-201512.csv'
subarea_profile_2015_shift = pd.read_csv(os.path.join(filedir, filename), index_col=0)

We now concatenate the data.

In [4]:
spp_subarea_profile = pd.concat(subarea_profile_by_month)
spp_subarea_profile = pd.concat([subarea_profile_2015_shift.iloc[-7:], spp_subarea_profile.iloc[:-7]])

In [5]:
spp_subarea_profile

,CSWS,EDE,GRDA,INDN,KACY,KCPL,LES,MPS,NPPD,OKGE,OPPD,SECI,SPRM,SPS,WAUE,WFEC,WR
MarketHour,,,,,,,,,,,,,,,,,
1/1/2016,5517.880333,682.513583,636.361250,130.541500,264.749167,1792.735250,438.084667,1112.545417,1915.848000,3643.126750,1515.893917,741.075083,398.912833,3551.144667,3583.095167,1104.741750,3534.467000
1/1/2016 1:00,5637.194833,688.033250,642.581000,132.113583,273.009333,1819.316083,446.326333,1129.076167,1960.570583,3695.321583,1533.537500,756.717500,397.835083,3657.918417,3605.059250,1130.788000,3619.600333
1/1/2016 2:00,5550.811750,677.512250,637.990667,127.038333,268.346917,1760.775750,434.564667,1102.867167,1918.712917,3661.685750,1496.289333,742.183083,386.183333,3632.676417,3542.124917,1135.679167,3542.137333
1/1/2016 3:00,5440.012750,665.806333,631.724250,122.935500,263.136417,1706.356583,421.382333,1080.234583,1875.326250,3604.736167,1457.130500,727.217000,375.261833,3582.520417,3483.046583,1129.893333,3464.693833
1/1/2016 4:00,5318.621500,656.705250,626.014750,117.485583,257.408583,1655.954250,407.680667,1056.503333,1836.165500,3541.218250,1410.668917,713.732250,364.861167,3533.605583,3425.512583,1123.064083,3395.328417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12/31/2016 19:00,4672.188000,496.779000,566.571000,106.905000,223.838000,1675.174000,365.567000,838.740000,1682.659000,2963.894000,1307.941000,605.739000,298.034000,3364.144000,2983.331000,985.943000,2966.550000
12/31/2016 20:00,4518.117000,477.577000,554.876000,104.983000,220.430000,1630.098000,358.194000,829.755000,1631.426000,2913.099000,1277.540000,600.183000,292.243000,3324.359000,2929.446000,949.597000,2944.317000
12/31/2016 21:00,4411.485000,465.076000,549.515000,103.593000,218.198000,1605.179000,350.014000,817.832000,1595.591000,2866.414000,1255.452000,591.050000,287.437000,3274.791000,2890.183000,923.479000,2955.879000
12/31/2016 22:00,4330.956000,463.437000,548.605000,104.192000,218.312000,1591.310000,347.423000,832.452000,1587.007000,2833.265000,1241.307000,591.300000,288.079000,3252.018000,2899.017000,910.477000,3002.412000
12/31/2016 23:00,4336.110000,476.441000,554.734000,108.458000,221.958000,1648.422000,359.416000,868.534000,1616.390000,2862.893000,1274.936000,591.835000,297.578000,3251.731000,2947.865000,918.324000,3085.744000

Combine KCPL (Kansas City Power & Light) and INDN (Independence Power and Light)

In [6]:
spp_subarea_profile.columns = list(map(lambda x: x.strip(), spp_subarea_profile.columns))
spp_subarea_profile['KCPL'] = spp_subarea_profile['KCPL'] + spp_subarea_profile['INDN']

In [7]:
spp_subarea_profile = spp_subarea_profile.drop('INDN', 1)
spp_subarea_profile.rename(columns = {'KCPL': 'KCPL_INDN'}, inplace=True)

In [8]:
spp_subarea_profile.index = pd.date_range(start="2016-01-01", periods=366*24, freq="H", tz="UTC")

In [9]:
spp_subarea_profile.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8784 entries, 2016-01-01 00:00:00+00:00 to 2016-12-31 23:00:00+00:00
Freq: H
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CSWS       8784 non-null   float64
 1   EDE        8784 non-null   float64
 2   GRDA       8784 non-null   float64
 3   KACY       8784 non-null   float64
 4   KCPL_INDN  8784 non-null   float64
 5   LES        8784 non-null   float64
 6   MPS        8784 non-null   float64
 7   NPPD       8784 non-null   float64
 8   OKGE       8784 non-null   float64
 9   OPPD       8784 non-null   float64
 10  SECI       8784 non-null   float64
 11  SPRM       8784 non-null   float64
 12  SPS        8784 non-null   float64
 13  WAUE       8784 non-null   float64
 14  WFEC       8784 non-null   float64
 15  WR         8784 non-null   float64
dtypes: float64(16)
memory usage: 1.1 MB

Save profile

In [10]:
spp_subarea_profile.to_csv('spp_subarea_demand_profile.csv')

In [11]:
spp_subarea_profile

,CSWS,EDE,GRDA,KACY,KCPL_INDN,LES,MPS,NPPD,OKGE,OPPD,SECI,SPRM,SPS,WAUE,WFEC,WR
2016-01-01 00:00:00+00:00,5517.880333,682.513583,636.361250,264.749167,1923.276750,438.084667,1112.545417,1915.848000,3643.126750,1515.893917,741.075083,398.912833,3551.144667,3583.095167,1104.741750,3534.467000
2016-01-01 01:00:00+00:00,5637.194833,688.033250,642.581000,273.009333,1951.429666,446.326333,1129.076167,1960.570583,3695.321583,1533.537500,756.717500,397.835083,3657.918417,3605.059250,1130.788000,3619.600333
2016-01-01 02:00:00+00:00,5550.811750,677.512250,637.990667,268.346917,1887.814083,434.564667,1102.867167,1918.712917,3661.685750,1496.289333,742.183083,386.183333,3632.676417,3542.124917,1135.679167,3542.137333
2016-01-01 03:00:00+00:00,5440.012750,665.806333,631.724250,263.136417,1829.292083,421.382333,1080.234583,1875.326250,3604.736167,1457.130500,727.217000,375.261833,3582.520417,3483.046583,1129.893333,3464.693833
2016-01-01 04:00:00+00:00,5318.621500,656.705250,626.014750,257.408583,1773.439833,407.680667,1056.503333,1836.165500,3541.218250,1410.668917,713.732250,364.861167,3533.605583,3425.512583,1123.064083,3395.328417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-31 19:00:00+00:00,4672.188000,496.779000,566.571000,223.838000,1782.079000,365.567000,838.740000,1682.659000,2963.894000,1307.941000,605.739000,298.034000,3364.144000,2983.331000,985.943000,2966.550000
2016-12-31 20:00:00+00:00,4518.117000,477.577000,554.876000,220.430000,1735.081000,358.194000,829.755000,1631.426000,2913.099000,1277.540000,600.183000,292.243000,3324.359000,2929.446000,949.597000,2944.317000
2016-12-31 21:00:00+00:00,4411.485000,465.076000,549.515000,218.198000,1708.772000,350.014000,817.832000,1595.591000,2866.414000,1255.452000,591.050000,287.437000,3274.791000,2890.183000,923.479000,2955.879000
2016-12-31 22:00:00+00:00,4330.956000,463.437000,548.605000,218.312000,1695.502000,347.423000,832.452000,1587.007000,2833.265000,1241.307000,591.300000,288.079000,3252.018000,2899.017000,910.477000,3002.412000
2016-12-31 23:00:00+00:00,4336.110000,476.441000,554.734000,221.958000,1756.880000,359.416000,868.534000,1616.390000,2862.893000,1274.936000,591.835000,297.578000,3251.731000,2947.865000,918.324000,3085.744000