In [1]:
import pandas as pd
import numpy as np

Read in 2016 MISO demand data

In [27]:
LRZ_demand_2016 = pd.read_excel('20161231_dfal_hist.xls', skiprows=5)
LRZ_demand_2016

,MarketDay,HourEnding,LoadResource Zone,MTLF (MWh),ActualLoad (MWh)
0,2016-01-01 00:00:00,1,LRZ1,10692,10911.1
1,2016-01-01 00:00:00,1,LRZ2_7,15766,15824.5
2,2016-01-01 00:00:00,1,LRZ3_5,9728,10006.7
3,2016-01-01 00:00:00,1,LRZ4,5043,5198.81
4,2016-01-01 00:00:00,1,LRZ6,10046,9963.71
5,2016-01-01 00:00:00,1,LRZ8_9_10,16748,17483.8
6,2016-01-01 00:00:00,1,MISO,68023,69388.7
7,2016-01-01 00:00:00,2,LRZ1,10403,10560.7
8,2016-01-01 00:00:00,2,LRZ2_7,15313,15271.2
9,2016-01-01 00:00:00,2,LRZ3_5,9579,9879.14
10,2016-01-01 00:00:00,2,LRZ4,4943,4968.12
11,2016-01-01 00:00:00,2,LRZ6,9967,9842.67
12,2016-01-01 00:00:00,2,LRZ8_9_10,16537,17122
13,2016-01-01 00:00:00,2,MISO,66742,67643.7
14,2016-01-01 00:00:00,3,LRZ1,10046,10211.5
15,2016-01-01 00:00:00,3,LRZ2_7,14827,14792
16,2016-01-01 00:00:00,3,LRZ3_5,9403,9751.33
17,2016-01-01 00:00:00,3,LRZ4,4833,4858.49
18,2016-01-01 00:00:00,3,LRZ6,9808,9740.47
19,2016-01-01 00:00:00,3,LRZ8_9_10,16276,16969.4
20,2016-01-01 00:00:00,3,MISO,65193,66323.2
21,2016-01-01 00:00:00,4,LRZ1,9784,9977.08
22,2016-01-01 00:00:00,4,LRZ2_7,14745,14462.1
23,2016-01-01 00:00:00,4,LRZ3_5,9255,9602.58
24,2016-01-01 00:00:00,4,LRZ4,4738,4831.48
25,2016-01-01 00:00:00,4,LRZ6,9678,9629.32
26,2016-01-01 00:00:00,4,LRZ8_9_10,16008,16820.7
27,2016-01-01 00:00:00,4,MISO,64208,65323.3
28,2016-01-01 00:00:00,5,LRZ1,9696,9870.24
29,2016-01-01 00:00:00,5,LRZ2_7,14688,14392.4
...,...,...,...,...,...
61512,2016-12-31 00:00:00,21,LRZ1,11976,NaN
61513,2016-12-31 00:00:00,21,LRZ2_7,17624,NaN
61514,2016-12-31 00:00:00,21,LRZ3_5,9737,NaN
61515,2016-12-31 00:00:00,21,LRZ4,5352,NaN
61516,2016-12-31 00:00:00,21,LRZ6,10069,NaN
61517,2016-12-31 00:00:00,21,LRZ8_9_10,17683,NaN
61518,2016-12-31 00:00:00,21,MISO,72441,NaN
61519,2016-12-31 00:00:00,22,LRZ1,11651,NaN
61520,2016-12-31 00:00:00,22,LRZ2_7,17156,NaN
61521,2016-12-31 00:00:00,22,LRZ3_5,9645,NaN
61522,2016-12-31 00:00:00,22,LRZ4,5294,NaN
61523,2016-12-31 00:00:00,22,LRZ6,9892,NaN
61524,2016-12-31 00:00:00,22,LRZ8_9_10,17476,NaN
61525,2016-12-31 00:00:00,22,MISO,71114,NaN
61526,2016-12-31 00:00:00,23,LRZ1,11351,NaN
61527,2016-12-31 00:00:00,23,LRZ2_7,16556,NaN
61528,2016-12-31 00:00:00,23,LRZ3_5,9522,NaN
61529,2016-12-31 00:00:00,23,LRZ4,5203,NaN
61530,2016-12-31 00:00:00,23,LRZ6,9663,NaN
61531,2016-12-31 00:00:00,23,LRZ8_9_10,17293,NaN
61532,2016-12-31 00:00:00,23,MISO,69588,NaN
61533,2016-12-31 00:00:00,24,LRZ1,10955,NaN
61534,2016-12-31 00:00:00,24,LRZ2_7,15858,NaN
61535,2016-12-31 00:00:00,24,LRZ3_5,9213,NaN
61536,2016-12-31 00:00:00,24,LRZ4,5047,NaN
61537,2016-12-31 00:00:00,24,LRZ6,9415,NaN
61538,2016-12-31 00:00:00,24,LRZ8_9_10,16828,NaN
61539,2016-12-31 00:00:00,24,MISO,67316,NaN
61540,NaN,NaN,NaN,NaN,NaN
61541,MISO MAKES NO REPRESENTATIONS OR WARRANTIES OF...,NaN,NaN,NaN,NaN

Replace nans with predicted values

In [ ]:
LRZ_demand.loc[LRZ_demand['ActualLoad (MWh)'].isna() , 'ActualLoad (MWh)'] = LRZ_demand['MTLF (MWh)']
LRZ_demand

Read in 2015 MISO demand data

In [4]:
LRZ_demand_2015 = pd.read_excel('C:\\Users\\dmuldrew\\Dropbox (IVL)\\Explorations\\DanM\\20151231_dfal_hist.xls', skiprows=5)
LRZ_demand_2015

,MarketDay,HourEnding,LoadResource Zone,MTLF (MWh),ActualLoad (MWh)
0,2015-01-01 00:00:00,1,LRZ1,11881,11566.6
1,2015-01-01 00:00:00,1,LRZ2_7,16777,16866.8
2,2015-01-01 00:00:00,1,LRZ3_5,10544,10673.9
3,2015-01-01 00:00:00,1,LRZ4,5620,5687.05
4,2015-01-01 00:00:00,1,LRZ6,11476,11594.3
5,2015-01-01 00:00:00,1,LRZ8_9_10,19013,18887.4
6,2015-01-01 00:00:00,1,MISO,75311,75275.9
7,2015-01-01 00:00:00,2,LRZ1,11445,11128.9
8,2015-01-01 00:00:00,2,LRZ2_7,16096,16232.9
9,2015-01-01 00:00:00,2,LRZ3_5,10283,10440.8
10,2015-01-01 00:00:00,2,LRZ4,5444,5540.74
11,2015-01-01 00:00:00,2,LRZ6,11277,11449.8
12,2015-01-01 00:00:00,2,LRZ8_9_10,18606,18462.7
13,2015-01-01 00:00:00,2,MISO,73151,73255.8
14,2015-01-01 00:00:00,3,LRZ1,11068,10744.2
15,2015-01-01 00:00:00,3,LRZ2_7,15626,15752.6
16,2015-01-01 00:00:00,3,LRZ3_5,10084,10206.7
17,2015-01-01 00:00:00,3,LRZ4,5341,5436.4
18,2015-01-01 00:00:00,3,LRZ6,11151,11292.1
19,2015-01-01 00:00:00,3,LRZ8_9_10,18394,18250.7
20,2015-01-01 00:00:00,3,MISO,71664,71682.7
21,2015-01-01 00:00:00,4,LRZ1,10870,10516.3
22,2015-01-01 00:00:00,4,LRZ2_7,15325,15413
23,2015-01-01 00:00:00,4,LRZ3_5,9962,10086.3
24,2015-01-01 00:00:00,4,LRZ4,5271,5361.72
25,2015-01-01 00:00:00,4,LRZ6,11106,11198.6
26,2015-01-01 00:00:00,4,LRZ8_9_10,18289,18014.3
27,2015-01-01 00:00:00,4,MISO,70823,70590.3
28,2015-01-01 00:00:00,5,LRZ1,10765,10369.1
29,2015-01-01 00:00:00,5,LRZ2_7,15274,15325.2
...,...,...,...,...,...
61344,2015-12-31 00:00:00,21,LRZ1,12717,12225
61345,2015-12-31 00:00:00,21,LRZ2_7,19129,18441.5
61346,2015-12-31 00:00:00,21,LRZ3_5,11451,11249.2
61347,2015-12-31 00:00:00,21,LRZ4,5947,5727.29
61348,2015-12-31 00:00:00,21,LRZ6,11453,11011.6
61349,2015-12-31 00:00:00,21,LRZ8_9_10,19469,19286.6
61350,2015-12-31 00:00:00,21,MISO,80166,77941.2
61351,2015-12-31 00:00:00,22,LRZ1,12319,11868.5
61352,2015-12-31 00:00:00,22,LRZ2_7,18487,17831.5
61353,2015-12-31 00:00:00,22,LRZ3_5,11215,10982.8
61354,2015-12-31 00:00:00,22,LRZ4,5843,5560.36
61355,2015-12-31 00:00:00,22,LRZ6,11229,10746.6
61356,2015-12-31 00:00:00,22,LRZ8_9_10,19046,18881.5
61357,2015-12-31 00:00:00,22,MISO,78139,75871.3
61358,2015-12-31 00:00:00,23,LRZ1,11940,11525.2
61359,2015-12-31 00:00:00,23,LRZ2_7,17699,17238
61360,2015-12-31 00:00:00,23,LRZ3_5,10933,10760.1
61361,2015-12-31 00:00:00,23,LRZ4,5670,5403.62
61362,2015-12-31 00:00:00,23,LRZ6,10940,10484.2
61363,2015-12-31 00:00:00,23,LRZ8_9_10,18481,18448.1
61364,2015-12-31 00:00:00,23,MISO,75663,73859.3
61365,2015-12-31 00:00:00,24,LRZ1,11510,11104
61366,2015-12-31 00:00:00,24,LRZ2_7,16856,16538.1
61367,2015-12-31 00:00:00,24,LRZ3_5,10524,10281.2
61368,2015-12-31 00:00:00,24,LRZ4,5443,5382.65
61369,2015-12-31 00:00:00,24,LRZ6,10611,10198.9
61370,2015-12-31 00:00:00,24,LRZ8_9_10,17711,17926.4
61371,2015-12-31 00:00:00,24,MISO,72655,71431.1
61372,NaN,NaN,NaN,NaN,NaN
61373,MISO MAKES NO REPRESENTATIONS OR WARRANTIES OF...,NaN,NaN,NaN,NaN

In [28]:
miso_zones = ['LRZ1','LRZ2_7','LRZ3_5','LRZ4','LRZ6','LRZ8_9_10']

def CreateDemandProfile(data, miso_zones, startdate, enddate):
    demand = pd.DataFrame(data[data['LoadResource Zone'] == miso_zones[0]]['ActualLoad (MWh)'])
    for zone in range(1,len(miso_zones)):
        demand[miso_zones[zone]] = data[data['LoadResource Zone'] == miso_zones[zone]]['ActualLoad (MWh)'].to_list()
    demand.columns = miso_zones
    
    #start_date = pd.to_datetime(startdate)
    #end_date = pd.to_datetime(enddate)
    #time_interval = pd.date_range(start_date, end_date, tz = "US/Eastern", freq='H')
    #demand.index = time_interval
    #demand.tz_convert('utc')
    
    return demand

In [29]:
startdate = pd.to_datetime('2015-10-01 01:00:00')
enddate = pd.to_datetime('2016-12-01 00:00:00')
MISO_loadzones_2015 = CreateDemandProfile(LRZ_demand_2015, miso_zones, startdate, enddate)
MISO_loadzones_2015

          LRZ1    LRZ2_7    LRZ3_5     LRZ4      LRZ6  LRZ8_9_10
0      11566.6  16866.75  10673.85  5687.05  11594.30   18887.39
7      11128.9  16232.87  10440.79  5540.74  11449.76   18462.71
14     10744.2  15752.56  10206.73  5436.40  11292.13   18250.65
21     10516.3  15413.05  10086.26  5361.72  11198.64   18014.31
28     10369.1  15325.18  10041.79  5324.75  11125.65   17934.87
35     10335.9  15472.11  10154.53  5354.31  11255.00   18008.60
42     10501.8  15799.27  10318.95  5434.42  11418.44   18302.87
49     10702.6  16185.31  10519.45  5537.95  11564.77   18668.21
56     10847.4  16334.72  10527.70  5524.95  11501.08   18806.34
63     11065.2  16781.55  10649.18  5593.12  11611.09   19275.53
70       11341  17267.23  10721.42  5690.01  11551.59   19755.16
77     11535.3  17625.63  10621.72  5711.36  11477.15   20001.94
84       11634  17730.18  10496.69  5635.19  11290.66   19972.88
91       11507  17641.26  10303.81  5547.19  11009.79   19671.56
98       11392  17510.16  10079.17  5434.51  10761.25   19300.72
105    11321.6  17390.50   9959.73  5356.84  10679.31   19060.51
112    11396.7  17682.00  10054.17  5434.04  10828.41   19026.25
119    11873.8  19020.16  10400.68  5721.76  11507.53   19256.95
126    12756.2  19638.80  11121.79  6087.07  11974.77   20173.34
133    12806.2  19392.67  11127.61  6062.48  11922.47   20312.60
140    12634.5  19002.38  10978.59  5977.13  11787.40   20078.84
147    12388.2  18439.02  10814.71  5873.40  11619.90   19692.24
154    12014.3  17546.17  10512.34  5700.15  11249.62   19095.28
161    11470.6  16505.33  10026.03  5437.31  10862.35   18215.47
168    11107.2  15700.75   9624.66  5229.74  10498.94   17395.15
175    10747.3  15107.56   9353.49  5102.10  10373.13   16772.80
182    10520.8  14782.72   9249.84  5031.66  10289.96   16317.91
189    10477.2  14636.38   9169.48  5009.15  10330.25   16071.00
196    10532.9  14799.93   9223.50  5037.47  10420.73   16004.05
203      10718  15349.01   9449.94  5124.52  10722.75   16193.43
...        ...       ...       ...      ...       ...        ...
61162  13240.8  20682.53  11778.62  6252.61  11928.72   19124.70
61169  13171.9  20370.56  11748.78  6156.06  11854.86   19608.10
61176  12944.6  19833.79  11545.58  6062.76  11683.20   19516.53
61183    12657  19170.98  11322.59  5952.61  11483.77   19284.26
61190  12151.3  18091.04  10979.51  5736.97  11061.17   18806.79
61197  11536.7  16816.69  10405.57  5486.17  10607.04   18001.21
61204  11068.2  15745.83   9908.59  5201.31  10215.56   17159.76
61211  10616.1  15057.94   9550.13  4998.84   9953.64   16533.92
61218    10279  14628.97   9421.95  4886.56   9794.41   16280.05
61225  10113.4  14425.16   9377.40  4803.83   9761.94   16136.29
61232  10050.2  14460.21   9407.82  4822.66   9831.34   16271.25
61239  10234.2  14947.22   9638.56  4797.85  10030.84   16539.99
61246  10718.8  15806.00  10014.47  5053.58  10416.97   17326.37
61253  11510.5  16766.03  10530.48  5352.12  10806.86   18411.88
61260    12043  17372.83  10883.51  5526.83  10983.90   18943.29
61267  12232.5  17807.42  11148.71  5539.40  11139.65   19278.06
61274  12386.9  18239.81  11150.76  5675.43  11308.75   19416.46
61281  12423.9  18405.98  11095.00  5746.53  11350.11   19162.18
61288  12314.6  18352.58  10914.79  5730.54  11302.29   18712.87
61295  12169.7  18182.98  10786.56  5729.29  11204.61   18276.43
61302  12077.5  18018.99  10697.41  5704.58  11205.52   18039.62
61309  11925.7  17882.76  10545.63  5655.86  11202.17   17845.32
61316  11885.4  18022.23  10520.71  5626.07  11202.79   17867.30
61323  12267.4  19087.44  10821.81  5815.40  11513.51   18298.59
61330  12863.1  19590.03  11604.49  6035.28  11606.52   19492.58
61337    12645  19112.33  11559.97  5871.35  11323.68   19621.66
61344    12225  18441.55  11249.20  5727.29  11011.60   19286.61
61351  11868.5  17831.50  10982.81  5560.36  10746.58   18881.53
61358  11525.2  17238.04  10760.08  5403.62  10484.22   18448.14
61365    11104  16538.11  10281.16  5382.65  10198.86   17926.37

[8760 rows x 6 columns]

In [30]:
start_date = pd.to_datetime('2016-10-01 01:00:00')
end_date = pd.to_datetime('2017-12-01 00:00:00')
MISO_loadzones_2016 = CreateDemandProfile(LRZ_demand_2016, miso_zones, startdate, enddate)
MISO_loadzones_2016

          LRZ1    LRZ2_7    LRZ3_5     LRZ4      LRZ6  LRZ8_9_10
0      10911.1  15824.53  10006.74  5198.81   9963.71   17483.79
7      10560.7  15271.17   9879.14  4968.12   9842.67   17121.95
14     10211.5  14792.03   9751.33  4858.49   9740.47   16969.39
21     9977.08  14462.12   9602.58  4831.48   9629.32   16820.69
28     9870.24  14392.40   9622.67  4804.95   9701.47   16797.15
35     9897.06  14541.61   9692.37  4856.01   9888.91   16965.46
42     10096.7  14886.83   9853.55  4970.98  10131.83   17392.22
49     10296.6  15351.13  10111.77  5070.41  10315.24   17941.20
56     10506.7  15622.51  10188.25  5061.51  10352.28   18293.29
63     10617.4  16011.85  10070.44  5181.92  10481.42   18843.33
70     10853.8  16544.85  10076.23  5250.89  10637.38   19413.83
77     11006.5  16938.96  10002.35  5306.10  10810.02   19750.73
84     10963.3  17118.67   9952.27  5311.75  10791.26   19729.04
91     10793.5  17147.65   9841.26  5259.96  10655.56   19432.83
98     10599.3  17058.19   9629.69  5163.37  10471.05   19041.41
105    10470.3  17019.34   9550.10  5071.50  10411.15   18738.25
112      10422  17270.89   9567.78  5089.32  10474.93   18707.85
119    10904.1  18383.75   9874.15  5295.98  10919.36   19073.41
126      11910  19001.02  10520.37  5774.19  11306.26   20219.34
133      11940  18730.83  10718.01  5670.01  11274.82   20618.18
140    11810.6  18336.11  10683.51  5642.05  11219.51   20618.73
147    11583.7  17831.28  10583.49  5554.56  11045.93   20431.28
154    11246.8  17060.49  10339.72  5459.57  10830.08   20063.53
161    10793.9  16115.70   9933.79  5278.74  10449.99   19445.81
168    10403.4  15233.96   9558.87  5076.10  10133.13   18747.16
175    10057.9  14638.56   9334.06  4922.07   9956.57   18276.99
182    9768.37  14274.14   9166.84  4819.87   9880.90   17891.18
189    9663.17  14131.29   9145.37  4747.25   9774.05   17771.74
196    9633.31  14154.24   9172.71  4784.28   9838.39   17769.69
203    9653.36  14425.77   9324.50  4859.64   9949.40   18004.85
...        ...       ...       ...      ...       ...        ...
61330    12726  19949.63  10532.54  5796.72  11235.02   19516.64
61337  12570.3  19629.04  10524.73  5777.34  11289.93   20029.99
61344  12310.8  19229.70  10405.95  5748.45  11233.69   19898.81
61351  12006.4  18660.58  10231.46  5622.63  11065.93   19713.80
61358  11568.3  17858.44   9871.54  5494.43  10825.21   19244.49
61365  11065.8  16787.19   9418.45  5294.49  10363.41   18511.92
61372      NaN       NaN       NaN      NaN       NaN        NaN
61379      NaN       NaN       NaN      NaN       NaN        NaN
61386      NaN       NaN       NaN      NaN       NaN        NaN
61393      NaN       NaN       NaN      NaN       NaN        NaN
61400      NaN       NaN       NaN      NaN       NaN        NaN
61407      NaN       NaN       NaN      NaN       NaN        NaN
61414      NaN       NaN       NaN      NaN       NaN        NaN
61421      NaN       NaN       NaN      NaN       NaN        NaN
61428      NaN       NaN       NaN      NaN       NaN        NaN
61435      NaN       NaN       NaN      NaN       NaN        NaN
61442      NaN       NaN       NaN      NaN       NaN        NaN
61449      NaN       NaN       NaN      NaN       NaN        NaN
61456      NaN       NaN       NaN      NaN       NaN        NaN
61463      NaN       NaN       NaN      NaN       NaN        NaN
61470      NaN       NaN       NaN      NaN       NaN        NaN
61477      NaN       NaN       NaN      NaN       NaN        NaN
61484      NaN       NaN       NaN      NaN       NaN        NaN
61491      NaN       NaN       NaN      NaN       NaN        NaN
61498      NaN       NaN       NaN      NaN       NaN        NaN
61505      NaN       NaN       NaN      NaN       NaN        NaN
61512      NaN       NaN       NaN      NaN       NaN        NaN
61519      NaN       NaN       NaN      NaN       NaN        NaN
61526      NaN       NaN       NaN      NaN       NaN        NaN
61533      NaN       NaN       NaN      NaN       NaN        NaN

[8784 rows x 6 columns]

In [ ]:
demand_15_16 = pd.concat([MISO_loadzones_2015, MISO_loadzones_2016])
sstart = pd.to_datetime('2016-01-01 00:00:00')
end = pd.to_datetime('2016-12-31 23:00:00')
MISO_demand_2016 = demand_15_16.loc[start:end]

In [ ]:
MISO_demand_2016.to_csv('miso_subarea_demand_profile_2016.csv')

In [ ]:
LRZ_demand = pd.read_excel('20161231_dfal_hist.xls')
LRZ_demand

In [ ]:
LRZ_demand.loc[LRZ_demand['ActualLoad (MWh)'].isna() , 'ActualLoad (MWh)'] = LRZ_demand['MTLF (MWh)']

In [ ]:
LRZ_demand

In [ ]:
LRZ_demand_2015 = pd.read_excel('C:\\Users\\dmuldrew\\Dropbox (IVL)\\Explorations\\DanM\\20151231_dfal_hist.xls', skiprows=5)
LRZ_demand_2015

In [ ]:
miso_zones = ['LRZ1','LRZ2_7','LRZ3_5','LRZ4','LRZ6','LRZ8_9_10']
MISO_loadzones_2015 = pd.DataFrame(LRZ_demand_2015[LRZ_demand_2015['LoadResource Zone'] == miso_zones[0]]['ActualLoad (MWh)'])
MISO_loadzones_2015.columns = [miso_zones[0]]
for zone in range(1,len(miso_zones)):
    MISO_loadzones_2015[miso_zones[zone]] = LRZ_demand_2015[LRZ_demand_2015['LoadResource Zone'] == miso_zones[zone]]['ActualLoad (MWh)'].to_list()

In [ ]:
start_date = pd.to_datetime('2015-01-01 01:00:00')
end_date = pd.to_datetime('2016-01-01 00:00:00')
time_interval = pd.date_range(start_date, end_date, tz = "US/Eastern", freq='H')
MISO_loadzones_2015.index = time_interval
MISO_loadzones_2015

In [ ]:
start_date = pd.to_datetime('2015-10-01 01:00:00')
end_date = pd.to_datetime('2016-12-01 00:00:00')

In [ ]:
MISO_loadzones = pd.DataFrame(LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ1']['ActualLoad (MWh)'])
MISO_loadzones.columns = ['LRZ1']

In [ ]:
MISO_loadzones['LRZ2_7'] = LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ2_7']['ActualLoad (MWh)'].to_list()

In [ ]:
MISO_loadzones['LRZ3_5'] = LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ3_5']['ActualLoad (MWh)'].to_list()

In [ ]:
MISO_loadzones['LRZ4'] = LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ4']['ActualLoad (MWh)'].to_list()

In [ ]:
MISO_loadzones['LRZ6'] = LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ6']['ActualLoad (MWh)'].to_list()

In [ ]:
MISO_loadzones['LRZ8_9_10'] = LRZ_demand[LRZ_demand['LoadResource Zone'] == 'LRZ8_9_10']['ActualLoad (MWh)'].to_list()

In [ ]:
MISO_loadzones

In [ ]:
start_date = pd.to_datetime('2016-01-01 01:00:00')
end_date = pd.to_datetime('2017-01-01 00:00:00')
time_interval = pd.date_range(start_date, end_date, tz = "US/Eastern", freq='H')

In [ ]:
MISO_loadzones.index = time_interval
MISO_loadzones

In [ ]:
demand_15_16 = pd.concat([MISO_loadzones_2015, MISO_loadzones])
demand_15_16

In [ ]:
start = pd.to_datetime('2016-03-13 00:00:00')
end = pd.to_datetime('2016-03-14 23:00:00')
preshift = demand_15_16.loc[start:end]
preshift

In [ ]:
utc_demand_15_16 = demand_15_16.tz_convert('utc')

In [ ]:
start = pd.to_datetime('2016-03-13 00:00:00')
end = pd.to_datetime('2016-03-14 23:00:00')
preshift = demand_15_16.loc[start:end]
preshift

In [ ]:
start = pd.to_datetime('2016-01-01 00:00:00')
end = pd.to_datetime('2016-12-31 23:00:00')
MISO_demand_2016 = utc_demand_15_16.loc[start:end]

In [ ]:
MISO_demand_2016

In [ ]:
import os
os.getcwd()

In [ ]:
MISO_demand_2016.to_csv('.\\Eastern_Demand_Improvement\\miso_subarea_demand_profile_2016.csv')

In [ ]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}
# us_state_abbrev = set(us_state_abbrev.values())

In [ ]:
state_to_MISO_demand_zones = {'North Dakota':'LRZ1', 'Montana':'LRZ1', 'South Dakota':'LRZ1','Minnesota':'LRZ1','Iowa':'LRZ3_5', 'Missouri':'LRZ3_5',\
'Wisconsin': 'LRZ2_7', 'Michigan': 'LRZ2_7', 'Illinois':'LRZ4','Indiana': 'LRZ6', 'Texas': 'LRZ8_9_10',\
'Louisiana': 'LRZ8_9_10','Arkansas':'LRZ8_9_10','Alabama':'LRZ8_9_10','Mississippi': 'LRZ8_9_10','Kentucky':'LRZ6'}

In [ ]:
import json
data = json.load(open('C:\\Users\\dmuldrew\\Downloads\\mapchartSave__usa_counties__.txt'))
data

In [ ]:
MISO_minority_report = {}
for val in data['groups'].values():
    MISO_minority_report[val['label']] = set(val['paths'])
MISO_minority_report

In [ ]:
bus_ba_map = pd.read_csv("C:\\Users\\dmuldrew\\Dropbox (IVL)\\Explorations\\BainanX\\Eastern Demand Improvement\\bus_ba_map.csv", index_col = 0)
bus_ba_map

In [ ]:
miso = bus_ba_map[bus_ba_map['BA'] == 'MISO']
miso

In [ ]:
miso['state'] = miso['County'].str.split('__').str[-1]
miso

In [ ]:
inverted_us_state_abbrev = {val:key for key,val in us_state_abbrev.items()}
inverted_us_state_abbrev

In [ ]:
state_to_MISO_demand_zones

In [ ]:
def get_MISO_demand_zone(inverted_us_state_abbrev, state_to_MISO_demand_zones, state_abbrev):
    mapped_zone = np.nan
    valid_state_abbrev = state_abbrev in inverted_us_state_abbrev.keys()
    if valid_state_abbrev:
        in_MISO_mapping = inverted_us_state_abbrev[state_abbrev] in state_to_MISO_demand_zones
        if in_MISO_mapping:
            mapped_zone =  state_to_MISO_demand_zones[inverted_us_state_abbrev[state_abbrev]]
    return mapped_zone

In [ ]:
get_MISO_demand_zone(inverted_us_state_abbrev, state_to_MISO_demand_zones,'CA')

In [ ]:
from functools import partial
MISO_demand_zone = partial(get_MISO_demand_zone,inverted_us_state_abbrev,state_to_MISO_demand_zones)

In [ ]:
miso['miso_zone'] = miso.apply(lambda x: MISO_demand_zone(x['state']), axis=1)
miso

In [ ]:
miso[miso['miso_zone'].isnull()].state.unique()

In [ ]:
miso[miso['miso_zone'].isnull()]

In [ ]:
miso.loc[40644,'miso_zone'] = 'LRZ2_7'

In [ ]:
MISO_minority_report

In [ ]:
miso[miso['County'] == 'Chippewa__WI']

In [ ]:
miso_copy = miso

for zone,counties in MISO_minority_report.items():
    for county in counties:
        print(county)
        print(zone)
        miso_copy.loc[miso['County'] == county,'miso_zone'] = zone
        print(miso_copy[miso['County'] == county]['miso_zone'])

In [ ]:
miso_copy

In [ ]:
miso_copy.to_csv('.\\Eastern_Demand_Improvement\\MISO_mapping.csv')